name: Lab 3 MVC CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install cpplint
        run: pip3 install cpplint
      - name: Lint C++ files
        run: |
          cd mvc/src
          echo "filter=-legal/copyright, -readability/todo, -build/namespaces_literals, -build/include_subdir, -whitespace/indent_namespace, -build/namespaces, -runtime/references
          linelength=120" > CPPLINT.cfg
          cpplint --recursive .
